- api.yaml
- package-lock.json
When creating realistic examples for the structure endpoint, I realized that we would need tabDefinitions for webViews ans views that will exist in app only. Let's discuss it...
> ZONA Structure: changed storyViewTab to webView Tab and introduced nativeOnlyViewTab plus examples

- api.yaml
- package-lock.json
Mit Prepublic habe ich besprochen, dass die Tabs in der Regel ein subMenu-Array haben und der erste Eintrag dieses Menüs initial geladen wird. 
* Ich habe das subMenu als property des tabDefinitionBase eingeführt
* Ich habe die tabDefinitionNativeOnly in tabDefinitionStory umbenannt. Sie ist für Tabs vorgesehen, in denen wir eine instagram-artige Story zeigen, aber kein subMenu.
* Die subMenus habe ich für alle Tabs mit echten Titeln und uuids in die examples konfiguriert.
* Die cpSelection war bisher ein Array mit cpItems. Jetzt gibt es die cpSelectuon nicht mehr, sondern nur noch pro menuEntryNative eine cpItem. Darin steckt die uuid, mit der die App Content von der cp-API holen kann.
> subMenu for tabs

- Pipfile
- Pipfile.lock
- api.yaml
- bin/ci
- bin/swagger-cli
- bin/test
- package-lock.json
- package.json
Damit wir keine Tippfehler etc. einchecken, lassen wir das API yaml jetzt überprüfen.
Zum einen vom swagger validator (der halbwegs brauchbare Fehlermeldungen hat), und zum anderen vom python-tooling, das wir auch in zeit.web verwenden (das leider nur "druckt nicht" meldet).
> ZON-6127: Validate API spec (mostly by CI)

- .editorconfig
- api.yaml
- codingstyle.rst
- index.rst
* Indentation: 2 Leerzeichen
(Listen immer einrücken, auch wenn der yaml-Standard es dort nicht zwingend verlangt)
* Strings quoten mit Double Quotes (``"foobar"``, NICHT ``'foobar'``)
* Identifier nicht quoten (``type: string``, NICHT ``type: "string"``)
* Leerzeilen zwischen inhaltlichen Abschnitten verwenden
* Inline Listen/Dicts höchstens bei Beispielen verwenden (z.B. ``example: ["zplus"]``), sonst immer neue Zeile und einrücken
* Schema-Objekte verwenden CamelCase mit Großbuchstaben vorn
(z.B. ``CenterpageElement``, ``TabDefinitionBase``)
* Properties verwenden Snake-Case und werden klein geschrieben
(z.B. ``base_url``, ``date_first_published``)
> MAINT: Define and apply a (hopefully consistent) YAML coding style

- api.yaml
Open for discussion. 
Eine Art `kind` bräuchten die areas und vielleicht die regions ja auch. Aber ob man das alles in einem Topf will … ob es bei Teasern besser `context` oder `content_type` heißen sollte … 🤔 
~Im Moment ist `kind` noch nicht required. Das ist für die Teaser eigentlich verkehrt.~ Wenn es required wird, muss man es auch gleich auf region und area draufstreuseln …
> ZON-6143 ff: Add more teaser types

- api.yaml
- codingstyle.rst
* Indentation: 2 Leerzeichen
(Listen immer einrücken, auch wenn der yaml-Standard es dort nicht zwingend verlangt)
* Strings quoten mit Double Quotes (``"foobar"``, NICHT ``'foobar'``)
* Identifier nicht quoten (``type: string``, NICHT ``type: "string"``)
* Leerzeilen zwischen inhaltlichen Abschnitten verwenden
* Inline Listen/Dicts höchstens bei Beispielen verwenden (z.B. ``example: ["zplus"]``), sonst immer neue Zeile und einrücken
* Schema-Objekte verwenden CamelCase mit Großbuchstaben vorn
(z.B. ``CenterpageElement``, ``TabDefinitionBase``)
* Properties verwenden snake_case und werden klein geschrieben
(z.B. ``base_url``, ``date_first_published``)
* Identifier verwenden kebab-case und werden klein geschrieben
(z.B. ``zplus-register``, ``menu-entry-native``)
> ZAPPI Coding style 2.0 RFC

- api.yaml
Laut Konzept wollen wir bevorzugt die _fertigen_ Infos in die Apps geben. Das wäre für den Link zu den Kommentaren der Link-Text, nicht die Anzahl der Kommentare als Integer. Analog zu den Galerien.
> MAINT: Use link label for comments

- api.yaml
Mit ZeitOnline/zeit.web#4193 sollten nur noch bekannte teaser layouts und badges ausgegeben werden.
> MAINT: Update teaser layouts and badges

- api.yaml
Prepublic wollen Teaser auf der obersten Ebene, wenn es keinen Sinn ergibt, sie in einen Container zu stecken. Zusätzlich werden ein paar neue Layouts hinzugefügt.
> ZON-6134: Enable teaser modules at top level

- api.yaml
otherwise the validation itself is suppressed as an "unknown response".
this enables the helpful error messages from pyramid_openapi
> ZON-6179: specify openapi's error message

- api.yaml
fügt einen Merklisten Endpunkt zur API hinzu. Momentan kann dieser noch nicht genutzt werden, da die Authentifizierung noch aussteht. Zudem ist nicht sicher, ob die SSOID im Pfad mitgegeben wird. 
`docs-zappi/api.yaml`
Lokal `$ bin/serve`
https://zeit-online.atlassian.net/browse/ZON-6178
> ZON-6178: add bookmarks endpoint for API

- api.yaml
it doesn't make sense for search results (or we could shoehorn the uuid
into it) but we don't actually need an id here so the easy solution is
to simply make it optional.
this change will then allow search results to use the existing
centerpage adapters and their content should "just work"
> ZON-6179: make id optional

- api.yaml
Fügt einen dem CenterpageVideoTeaser ein hasAdvertisement Attribut hinzu
docs-zappi/api.yaml
zeit.web/app/centerpage.py
im friedbert-deployment
$ bin/test zeit.web/src/zeit/web/app/test/test_centerpage.py
https://zeit-online.atlassian.net/browse/ZON-6248
> ZON-6248: add Advertisement attribute to api

- api.yaml
the backend no longer dictates the presentation of the image, instead
clients can decide themselves (and have the means to request any variant
they chose via the baseURL)
> ZON-6266: remove variant and ratio from image spec

- api.yaml
1. Fügt Authentifizierung mit einem SSO Cookie für den bookmarks API-Endpunkt hinzu. Die Authentifizierung ist absichtlich nicht auf root-Level eingebaut, um keine weiteren Komponenten der API zu beeinträchtigen. 
2. Das ReadingList Schema wurde entfernt. Die API liefert nun ein Teaser-Layout für Bookmark-Items aus, daher kann einfach das Centerpage-Schema genutzt werden. 
`api.yaml`
in zeit.web
`bin/test zeit.web/src/zeit/web/app/test/test_view_bookmarks`
https://zeit-online.atlassian.net/browse/ZON-6178
diese Authentifizierung ist für MVP-Zwecke gedacht und sollte zügig durch die gewünschte OpenID Connect Authentifizierung ersetzt werden.
> ZON-6178: bookmarks security schema

- api.yaml
Fuer Teaser wird jetzt auch die UUID des geteaseden Objektes ausgeliefert, damit sie direkt gebookmarked werden koennen
> ZON-6268 teaser UUID

- api.yaml
Stellt Endpunkte für das Hinzufügen und Entfernen von Einträgen der Merkliste bereit. Es muss ein sso_cookie mitgeschickt werden. 
Nach dem Mergen des zeit.web PRs:
`bin/test zeit.web/src/zeit/web/app/test/test_view_bookmarks.py`
https://zeit-online.atlassian.net/browse/ZON-6263
> ZON-6263: Post and delete bookmark entries

- api.yaml
this way intermediary servers needn't examine the payload to pass it on
and endpoints can focus on the store type they are responsible for.
> ZON-6314: express the app store type via path, not in the payload

- api.yaml
erlaubt uuids ohne geschweifte Klammern und "urn:uuid" Präfix im uuid Schema von Zappi. Vollstände uuids werden weiter unterstützt.
Nach dem Mergen des zeit.web PRs:
`bin/test zeit.web/src/zeit/web/app/test`
https://zeit-online.atlassian.net/browse/ZON-6268
> ZON-6268: Short uuids for Zappi

- api.yaml
Zappi kann Einträge zur Merkliste hinzufügen und entfernen und es gibt jetzt auch vernünftige error responses.
in zeit.web:
`bin/test zeit.web/src/zeit/web/app/test/test_view_bookmarks.py`
https://zeit-online.atlassian.net/browse/ZON-6263
> ZON-6263: Post and delete bookmark entries in Zappi

- api.yaml
Centerpages liefern nun die Metainformationen für die History.
`api.yaml`
in zeit.web `bin/test zeit.web/src/zeit/web/app/test/test_view_centerpage.py`
https://zeit-online.atlassian.net/browse/ZON-6327
> ZON-6327: Metainfos on centerpage

- api.yaml
Content der auf CPs eingebunden ist, soll wissen, ob er bookmarkable ist, oder nicht.
`api.yaml`
in zeit.web, wenn der PR gemerged ist
`bin/test zeit.web/src/zeit/web/app/test/test_centerpage.py -sk test_teaser_contains_bookmarkable_property `
https://zeit-online.atlassian.net/browse/ZON-6373
> ZON-6373: Boomarkable content

- api.yaml
this essentially is a manual and complete version of the auto-generated
spec from the profile server at
https://docs.zeit.de/comment/referenz/rest.html
since that spec is auto-generated (and thus more or less useless, since
it says nothing about the actual content) we recreate it here.
note that we (indirectly) signify the login status via return code. this
may or may not be a desirable behaviour but seems like a good, sparse
initial approach.
> ZON-6277: provide information about user

- api.yaml
@TStrothjohann passt das so mit den abo bezeichnungen? bin offen fuer vorschlaege.
ich habe mir gedacht, dass wenn wir das einfach als liste mit definiertem vokabular machen, ist es am flexibelsten her. und die clients koennen dann ja einfach sowas machen wie ``if 'pur' in info['subscriptions']``.
> ZON-6386: include subscriptions in user info

- api.yaml
Erlaubt Einträge für Header und Markups auf Centerpages in Zappi
`api.yaml`
in `zeit.web`:
`bin/test zeit.web/src/zeit/web/app/test/test_view_centerpage.py`
https://zeit-online.atlassian.net/browse/ZON-6383
> ZON-6383: Centerpage header

- api.yaml
Die Informationen level2, level3 und keywords werden von Zappi ausgespielt, damit sie als Ad-Informationen der IQD zur Verfügung gestellt werden können.
`zeit.web.app.spec.api.yaml`
in zeit.web:
`$ bin/test zeit.web/src/zeit/web/app/test/test_view_centerpage.py -sk test_zappi_returns_adcontroller_values_on_hp`
oder auf staging nach dem naechsten Release:
`https://zappi.staging.zeit.de/cp/index`
auf Centerpage Ebene `level2`, `level3` und `keywords` kontrollieren
https://zeit-online.atlassian.net/browse/ZON-6376
> ZON-6376: Adhandler-information for centerpage

- api.yaml
otherwise we have the absurd situation that openapi **request**
validation  detects an invalid
request, it produces a 400 with a (usually) helpful error message but if
400 is not a valid response, openapi's **response** validation produces
a 500 (without any useful information whatsoever)
this PR simply sprinkles 400 responses over those resources that haven't
declared them yet. henceforth we need to add them to begin with when
configuring new resources.
> MAINT: make the generic 400 responses valid for all resources

- api.yaml
while technically correct, in practice it throws validation errors when
posting verbatim values from the actual apple appstore, which are in
fact valid base64 encoded strings.
the pragmatic approach is to drop the formal specification and contend
with an informat spec that says "must be base64 encoded" in the
description
> FIX: don't specify ``bytes`` as format for iap payload

- api.yaml
Das Schema ist vielleicht ein bisschen _verbose_, aber dafür sehr unmissverständlich und generisch.
Ticket: https://zeit-online.atlassian.net/browse/ZON-6406
> ZON-6406: Add click tracking Parameter for teaser

- api.yaml
Follow-up zu https://github.com/ZeitOnline/zeit.web/pull/4547 . 
Reicht das so? Gibts irgendwo noch ein Changelog zu befüllen?
Beim Submodul-Updaten in zeit.web brauche ich dann nochmal Hilfe, bitte.
> MAINT: Remove unused webtrekk cp32 from API specs

- api.yaml
Ein Nutzer kann ein nicht ausgefülltes Profil haben, daher sollten die entsprechenden Parameter `nullable` sein. Der `username` heißt bei uns nur `name` und die `adControllerUserGroup` ist jetzt definiert.
> FIX: User endpoint

- api.yaml
Needed for correct caching in ZONA tab story
> added zon-teaser-upright to teaser layout enum

- api.yaml
zon-teaser-upright belongs into it's fancy new ZONA-only story area, which should be allowed.
> added story area

- api.yaml
Die API soll Audiodaten für Premium Audio Teaser ausgeben.
Ticket: https://zeit-online.atlassian.net/browse/ZON-6668
> ZON-6668: Add Schema for CenterpageTeaserAudio

- api.yaml
I have agreed with Andi and Pavel from Prepublic that it would be best two introduce a new area type for swipeables with fixed heights since headed(-light) is a very comlex module in both apps because of the variety of heights that have to be handled.
> added two area layouts

- api.yaml
I'm introducing zon-teaser-stripe as teaser layout for flat stripe-like teasers in the new audio tab of the ZON App.
> Allow zon-teaser-stripe

- api.yaml
Episode and series image properties for audio and podcast teasers.
> ZO-639: Episode and series images

- api.yaml
In this change I'm introducing new area types `link-list` and `podcast-grid`. I'm also adding teaser layouts `headerimage` aka "Panorama Aufmacher" in zeit.web, `zon-teaser-link-list-item` and `zon-teaser-cover`. All of them are needed to build the new audio tab's podcast overview.
> Allow new area types and teaser layouts

- api.yaml
Um in vivi die structure (z.B https://vivi.staging.zeit.de/repository/data/app/0-3-2/structure) validieren zu können, wird ein übergeordneter Schema Typ benötigt, in dem die entsprechenden Subschemata referenziert werden.
> ZO-1094: Implement structure summary schema

- api.yaml
Einfacher Endpunkt `/bookmark-ids` um die Merkliste lediglich als Liste von UUIDs auszugeben. Hierbei sparen wir uns den Elasticsearch-Request, sodass der Endpunkt performanter ist, als der `/bookmarks` Endpunkt.
> ZO-1266: Provide simple list endpoint for bookmark ids

- docs/api/api.yaml
In order to show linked titles above lists of teasers, I need a new area layout. I would call it standard-headed because “headed” areas are well known and standard areas, too.
> ZO-2035: Standard-headed area layout

- docs/api/api.yaml
The idea was to define several menus and reference them in menu-left|right properties of each tab. The schema allowed only one string, though.
> MAINT: remove restriction for menu-left|right properties

- docs/api/api.yaml
Die API Definition für die ['freebies' Routen](https://docs.zeit.de/freebies/onboarding.html#api) wird hinzugefügt.
Siehe [ZO-4296](https://zeit-online.atlassian.net/browse/ZO-4296) & https://github.com/ZeitOnline/zeit.web/pull/7282
[ZO-4296]: https://zeit-online.atlassian.net/browse/ZO-4296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ZO-4296: Add 'freebies' routes

- docs/api/api.yaml
In order to show zon-teaser-wide fullwidth in lead positions, they will be placed into a lead area. I therefore allow the lead area in zappi now.
> Allow area layout lead

- docs/api/api.yaml
Es steht bereits als Abnahmekriterium in der ZO-4579. Ich möchte es hier aber vorwegnehmen, weil die Apps die dossier area bereits darstellen können. Um das neue Layout auf nativen Seiten testen und nutzen zu können, brauche ich diese Anpassung. Sonst sind CPs mit diesen Area Layouts invalide...
> allow area layouts dossier and headed-carousel

- docs/api/api.yaml
Update links to refer to simplecast and add `ad-free-url` property to `TeaserPodcast`
> ZO-3689: Allow ad-free podcast link

- docs/api/api.yaml
ich habe die Auslieferung der Daten in der AreaBase verortet, da wir abgesprochen hatten, dass das für alle Areas gelten soll.
> ZO-4596: Zappi returns read_more_url and topiclinks of centerpages of areas

- docs/api/api.yaml
API Config für 'summy' "summaries" Endpunkt.
> ZO-4598: add 'summy' API endpoints

- docs/api/api.yaml
https://zeit-online.atlassian.net/browse/ZO-4579 sagt, dass das JSON für Areas auch die Spitzmarke (`supertitle`) enthalten soll. Dieser PR bereitet die Specs dafür vor. Der Output wird in https://github.com/ZeitOnline/zeit.web/pull/7615 umgesetzt.
> ZO-4595: Add supertitle to area specs

- docs/api/api.yaml
https://zeit-online.atlassian.net/browse/ZO-4579
> ZO-4579: Add readmore label to headed area

- docs/api/api.yaml
Consult corrections in merkl https://github.com/ZeitOnline/merkl/pull/387
> ZO-6181: sync updates from 'merkl' OpenAPI spec

- docs/api/api.yaml
Proposal...
linked-uuid as property of areaBase
region layout playlist
teaser layout audio-playlist-m-cover
Areas and headers don't have to have titles. Let's not require these properties anymore. It's causing validation errors.
> WCM-352_update-zappi-specs-for-playlists

- docs/api/api.yaml
It should be accessible for anonymous users as well.
Refs: ZO-4493, #136, #139
> fix(content): remove security restrictions for `/teaser` endpoint

- docs/api/api.yaml
For playlists that are no volumes we don't want to use a different layout in the apps. It's called audio-playlist-m.
> WCM-352: allow audio-playlist-m teaser layout

- docs/api/api.yaml
Wie im [Ticket](https://zeit-online.atlassian.net/browse/ZO-5759) beschrieben.
> ZO-5759: Add liveblog teaser events

- docs/api/api.yaml
Ticket: https://zeit-online.atlassian.net/browse/WCM-439
To present playlists as hero teasers and cp headers we need new teaser layouts...
- audio-playlist-header
- audio-playlist-header-cover
- audio-playlist-tile-l
- audio-playlist-tile-l-cover
> allow audio-playlist-header and audio-playlist-tile-l

- docs/api/api.yaml
Entsprechend der [Merkl-API](https://github.com/ZeitOnline/merkl/pull/469) auch hier die Ergänzung des Status 409, welcher beim Posten eines Bookmarks durch einen User zurückgegeben wird, wenn der Bookmark schon existiert. In Zappi führt das sonst zu einem 500er durch die Openapi Validierung.
> fix: add http status 409 to spec which is used for duplicates

- docs/api/api.yaml
Mit https://github.com/ZeitOnline/freebies/pull/150 kann die 'freebies' API jetzt auch 403er liefern.
> ZO-4648: declare status code for missing user entitlement

- docs/api/api.yaml
Fügt die API Docs für die Integration von CPExtras als Teil der `items` einer Centerpage im `/cp`-Endpunkt hinzu.
Siehe Beschreibung in https://github.com/ZeitOnline/zeit.web/pull/8742
> ES-72: Add CenterpageExtra (CPExtra) to Centerpage items

- .editorconfig
- .git-blame-ignore-revs
- docs/api/api.yaml
- docs/api/package-lock.json
- docs/api/package.json
- docs/api/prettier.config.js
Führt `@zeitonline/prettier-config` ein und ersetzt die `.editorconfig` durch die aus [ZeitOnline/frontend-code-style](https://github.com/ZeitOnline/frontend-code-style).
> MAINT: format api.yaml according to ZON standards

- docs/api/api.yaml
The app should show filters on `audio-filters` areas.
> allow new "audio-filters" area

- docs/api/api.yaml
zon-teaser-cell will be used to show authors in podcast cps. Let's allow it in ZAPPI...
> allow zon-teaser-cell

- docs/api/api.yaml
Fügt das neue PodcastMetadata CP-Modul hinzu.
Schwester-PR der das neue Schema implementiert: https://github.com/ZeitOnline/zeit.web/pull/9103
Ticket: https://zeit-online.atlassian.net/browse/ES-290
> ES-290: Add CenterpagePodcastMetadata schema

- docs/api/api.yaml
Wir haben festgestellt, dass diese Eigenschaft an verschiedenen Stellen unterschiedlich benannt ist. Dieser PR (und der Schwester-PR in zeit.web – https://github.com/ZeitOnline/zeit.web/pull/9144 ) gleicht das an.
> ES-340: Use consistent naming for followingType
