ZeitOnline/docs-zappi

- api.yaml
Dient als Diskussionsgrundlage und Merkzettel für mich.
- Brauchen wir `CenterpageAreaBase`? Oder ist das nicht gleichbedeutend mit `CenterpageArea`? Zumindest haben wir (noch) kein `CenterpageModuleTeaserBase` oder `CenterpageRegionBase` …
- Sind `link` und `title` von CenterpageAreaBase wirklich _required_ attributes? In Vivi / unserem Content ist das nicht gegeben. Wir können dann natürlich auch immer `''` ausgeben … aber warum sollten wir das tun?
> MAINT: Harmonize and expand API

- api.yaml
`TabDefinitionWebView` hatte übrigens keinerlei Verwendung und ist rausgeflogen.
> MAINT: Naming things

- api.yaml
> ZON-6127: add missing type menu-item-app

- api.yaml
> MAINT: Add `items` property to TabStory

- api.yaml
> ZON-6181: Add human readable date string

- api.yaml
this has already been implemented in zeit.web
> ZON-6149: support query parameters for image variants

- api.yaml
it now only relies on query parameters
> ZON-6149: adjust url structure for images

- api.yaml
FIX zu https://github.com/ZeitOnline/docs-zappi/commit/a8a809c3878005cf5c65fce2a5b20817fbc61f89
`$ bin/test zeit.web/src/zeit/web/app/test -sk test_`
> FIX: remove Authentication until 500er solved

- api.yaml
> ZON-6288: Add google podcast feed URL

- api.yaml
preliminary draft as basis for further discussion
> ZON-6303: provide endpoint to drop off purchase receipts

- api.yaml
Fügt der Api Adplaces auf Centerpage-Ebene hinzu.
`api.yaml`
wenn der zugehörige zeit.web PR gemerged ist:
`bin/test zeit.web/src/zeit/web/app/test/test_view_centerpage.py`
https://zeit-online.atlassian.net/browse/ZON-6153
> ZON-6153: Zappi adplaces

- api.yaml
added zon-teaser-classic to the list of possible values of layout.
> zon-teaser-classic as possible value of layout

- api.yaml
Staging und Production cookies für Zappi
api.yaml
Mit cookie!
`https://zappi.staging.zeit.de/0.3.1/bookmarks`
`https://zappi.zeit.de/0.3.1/bookmarks`
> FIX: Separate cookies for staging and production

- api.yaml
Icons für die MenuItems
`api.yaml`
https://zappi.zeit.de/0.3.1/structure
https://zeit-online.atlassian.net/browse/ZON-6272
> ZON-6272: Add icons to MenuItemBase

- api.yaml
> ZON-6364: Add schema for tracking data

- api.yaml
`http :9090/app/cp/0fd9480f-1b52-4fcb-942e-8089e378102e`
> FIX: ZON-6383 supertitle nullable

- Pipfile
- Pipfile.lock
- package-lock.json
- package.json
Bei mir brach `bin/test` mehrmals ab mit dem Hinweis:
```shell
bin/test                                                                                                                                                                                                 Di 11 Mai 15:45:25 2021
Installing dependencies from Pipfile.lock (e49269)...
🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 1/1 — 00:00:00
An error occurred while installing lxml==4.6.3 --hash=sha256:26e761ab5b07adf5f555ee82fb4bfc35bf93750499c6c7614bd64d12aaa67927 --hash=sha256:122fba10466c7bd4178b07dba427aa516286b846b2cbd6f6169141917283aae2 --hash=sha256:820628b7b3135403540202e60551e741f9b6d3304371712521be939470b454ec --hash=sha256:7610b8c31688f0b1be0ef882889817939490a36d0ee880ea562a4e1399c447a1 …
```
> MAINT: Update dependency packages

- api.yaml
> Add teaser layout zon-teaser-podcast-small

- api.yaml
It's a proposal: I just added properties of type string for visible-from and visible-to to the TabBase schema.
> ZO-1292: added visible-from and visible-to to TabBase

- docs/api/package-lock.json
- docs/api/package.json
- docs/onboarding.rst
- docs/operations.rst
> MAINT: Update node packages

- docs/api/api.yaml
Dieser PR erlaubt Autorenteaser.
> ZO-1941: Author teaser

- docs/api/api.yaml
(Diskussion zur Benamung am Ticket https://zeit-online.atlassian.net/browse/ZO-2395 )
> ZO-2395: Introduce new navigations to Zappi Specs

- docs/api/api.yaml
Merge after: https://github.com/ZeitOnline/zeit.web/pull/7344
> ZO-4255: Delete unused badges

- docs/api/api.yaml
Ticket: https://zeit-online.atlassian.net/browse/ZO-5265
> ZO-5265: Update API schema for TTS audio

- docs/api/api.yaml
> ZO-5719: duration can be null to support premium audios

- docs/api/api.yaml
> ZO-6158: allow headed-grid area layout

- docs/api/api.yaml
Erstmal neue Teaser....
audio-poster-m
audio-poster-l
audio-tile-s-collapsed
audio-tile-m-collapsed
audio-listitem-s-expanded
Damit es dann bald wieder weniger werden können...
> ZO-6207_new-zappi-audio-teaser-names

- docs/api/api.yaml
linked-uuid as property of areaBase  
region layout playlist  
teaser layout audio-playlist-m-cover
> add region layout playlist, linked-uuid and audio-playlist-cover

- docs/api/api.yaml
Ticket: [ZO-6400](https://zeit-online.atlassian.net/browse/ZO-6375)
[ZO-6400]: https://zeit-online.atlassian.net/browse/ZO-6400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ZO-6400_add-audio-moderation-teaser-layout

- docs/api/api.yaml
> WCM-438: Define background color for volume

- mkdocs.yml
This PR adds the team information to the mkdocs.yml file
> chore(docs): add team information to mkdocs

- docs/api/api.yaml
> docs: add documentation for merkl

- docs/api/api.yaml
Ref: https://zeitonline.slack.com/archives/C030B7G6ACQ/p1756824230626169
> fix: remove required params for bookmark
